name: Label Draft PRs Test

on: [push, workflow_dispatch]

jobs:
  label-draft-pr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch open pull requests
        id: fetch_prs
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/pulls
          query: |
            state=open
            per_page=100

      - name: Save PR data to file
        run: |
          echo '${{ steps.fetch_prs.outputs.data }}' > pr_data.json

      - name: Label draft pull requests
        run: |
          # Parse PR numbers of draft PRs and add the "draft" label
          for pr in $(jq -r '.[] | select(.draft == true) | .number' pr_data.json); do
            gh pr edit "$pr" --add-label "draft" --repo "${{ github.repository }}"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
